services:
  web:
    container_name: ${CONTAINER_NAME}
    build: .
    command: /bin/sh start.sh
    volumes:
      - .:/code
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/ # nginx
    ports:
      - "8999:8999"
    env_file:
      - .env