services:
  web:
    build: .
    command: /bin/sh start.sh
    volumes:
      - .:/code
    expose:
      - "8000"
    networks:
      - shared_network  # 使用共享网络

networks:
  shared_network:
    external: true  # 声明为外部已存在的网络