services:
  postgres:
    image: postgres:15-alpine
    container_name: app1-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    networks:
      - dj_network
    expose:
      - "5432"

  web:
    container_name: app1 # 启动多个django应用的时候，全局替换掉app1
    build: .
    command: /bin/sh start.sh
    volumes:
      - .:/code
    ports:
      - "${PORT}:8000"
    networks:
      - dj_network
    env_file:
      - .env

volumes:
  postgres_data:
    name: "postgres_data"

networks:
  dj_network:
    driver: bridge