services:
  web:
    container_name: hello-django
    build: .
    command: /bin/sh start.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - hello_network

  nginx:
    container_name: hello-nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/ssl
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web
    networks:
      - hello_network


networks:
  hello_network:
    driver: bridge